name: Spinnaker Pre Install
env:
  VERSION: docker
  #REGISTRY_URL: "gcr.io/spinnaker-marketplace/"
  IMAGE_NAME: "quay.azk8s.cn/coreos/prometheus-config-reloader:v0.36.0"

on:
  push:
    paths:
      - '.github/workflows/blank.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      
    - name: 01-获取镜像
      run: |
        docker pull ${IMAGE_NAME}
        docker save ${IMAGE_NAME} -o test.tar
        

    - name: 02- 生成文件
      run : |
        mv test.tar artifacts/

        
    ## artifact https://github.com/actions/upload-artifact
    - uses: actions/upload-artifact@v2
      with: 
        name: ${{ env.VERSION }}-Install
        path: artifacts/*
